### PR TITLE
Content Pass

### PR DESCRIPTION
**Pull request by orionthewake**
Added Android articles and courses from the past 2 years, and also adjusted the categories where needed.

### CODE REVIEW

**Comment by luke-freeman** [comment]
@orionthewake 

Hey Joe, 

I took a quick look over this branch from a design perspective and had a few suggestions. 

Should we use ‘&’ instead of ‘and’ for the element titles eg. Tips & Tricks, Activities & Fragments…

The color for the Security section is out of place. That blue/grey was planned for a section outside of the table eg. Also Good To Know. It would make more sense if Security was orange or yellow the next color after red. 

I had 3 content suggestion changes too: 

1. The Tips and Tricks card is more a process you can apply than an element of learning. What if you changed that cards title to ‘Android Studio’ and inside you had the tutorial for tips and tricks. 
2. The cheat sheet feels out of place. Should this have a link at the top of the page instead or be added to also nice to know?
3. Other UI feels kind of wedged in there and ambiguous. Could the tutorials in Other UI not be worked into the other columns. Alternatively you could start a new section called ‘More User Interface’ and have four fresh columns to fill.

**Comment by rwenderlich** [comment]
This looks great, thank you for putting this together @orionthewake. I can only imagine how much work this must have been to populate!

I made a few changes to the copy and added a (lame) joke to the end. Feel free to tweak. 

I also added an indicator for which resources are free, and which are premium (subscriber-only), since I think that is what I would want as a reader.

One request before this goes out @orionthewake - can you please add "elementDescription" for each element? That should describe what the element is (and shows up if you click on it). It's filled in for Kotlin, but nothing else.

**Comment by orionthewake** [comment]
Thanks @rwenderlich and @luke-freeman! I'll make the remaining requested changes and then update the branch and PR.

**Comment by luke-freeman** [comment]
@orionthewake @rwenderlich 

This is looking really great!

A few comments on Ray’s changes. 

The introduction is really good, very clear and direct. 

Please can we remove the joke :)

We have premium and free tags now and every article is free and every video is premium. Should we get rid of the article/video label and just have free/premium tags instead?

In some cases the tutorial titles are so long they become difficult to read. Especially in blocks of 4. Should we do some curation and reduce the titles so they still retain the key information. Eg. 

“Kotlin Generics Tutorial: Getting Started” 

could be changed to 

“Kotlin Generics: Getting Started”

or 

“Kotlin Generics”

**Comment by orionthewake** [comment]
@luke-freeman @rwenderlich I've incorporated your feedback and requested changes. The only thing I did not tackle was shortening the tutorial titles, since I did not want to lose the data that had been populated in the JSON. Feel free of course to shorten them if you wish.

For the Kotlin Cheat-Sheet, I just moved that element to the end of the Kotlin Language section, which you hopefully feel is a better fit for it.

I also removed one of the sections and added those 3 items to "Also good to know"

NOTE: Luke requested we NOT merge this branch until he has had a chance to fix an issue that he's seen on mobile.

**Comment by luke-freeman** [comment]
@orionthewake @rwenderlich 

I expanded the color classes and changed a few colors further down. I had to remove the joke it was too bad :) Any other ideas?

Thanks for all the great work on this!

I think it's ready to launch

**Pull request merged**
